#!/bin/bash

# 检查必要的命令是否存在
check_command() {
    if ! command -v "$1" &> /dev/null; then
        echo "错误：未找到 '$1' 命令，请先安装它！"
        exit 1
    fi
}

# 检查 Java 和 openapi-generator-cli
check_command "java"
check_command "openapi-generator-cli"

rm -rf ./3rdparty

json_path=./MelodixAPI.swagger.json
#json_path=./MelodixAPI.openapi.json
code_path="./3rdparty/MelodixAPI"

openapi-generator-cli generate \
    -i $json_path \
    -o $code_path \
    -g cpp-qt-client \
    --additional-properties="optionalProjectFile=false,modelNamePrefix=MD,packageName=QtMelodixAPI,cppNamespace=MelodixAPI" --skip-validate-spec

sed -i "s/value = QString::number(jval.toDouble());/value.setNum(jval.toDouble(),'f', 0);/g" 3rdparty/MelodixAPI/client/MDHelpers.cpp